### PR TITLE
WIP: Create API reference

### PR DESCRIPTION
**Pull request by TedDriggs**
This reference lists all supported attributes alphabetically.
It should in future link to examples and higher-level documentation.

Part of #232

### CODE REVIEW

**Comment by TedDriggs** [comment]
@andy128k can you take a look at this? I'm going to keep working away at getting all the options captured, and would appreciate a second set of eyes looking for errors and omissions.

**Comment by andy128k** [comment]
I think it would be hard to maintain such document unless it is managed/covered by `cargo doc`.

**Comment by TedDriggs** [comment]
I wish there was a way to use `cargo doc` over our options structs to auto-generate this, but the options structs aren't public; `derive_builder_core` deliberately only exposes `builder_for_struct(DeriveInput) -> TokenStream` so that adding new options doesn't force us to rev the crate version.

Even `serde` doesn't seem to have a good way of generating this documentation; it's kept separately ([example](https://github.com/serde-rs/serde-rs.github.io/blob/master/_src/field-attrs.md))

The current approach with a flat list of features in README.md isn't working - see #224 and #225 as recent examples where that's failed.

I'm hoping that the rate of API changes for `derive_builder` will be slow going forward; the crate seems pretty mature, and I'm increasingly conservative in what changes we should accept. I therefore _think_ it'll be possible to manually enforce that any macro API change PR must have an update to this file.

**Comment by indietyp** [comment]
There are also things like: https://docs.rs/binread/latest/binread/attribute/index.html, which create an additional documentation-only module.

**Pull request closed without merging**
