### PR TITLE
Fix typo in custom setter documentation

### PR DESCRIPTION
**Pull request by Adam-Gleave**
Thanks for the great work on this crate!

I found a typo while I was reading through the docs of this crate today, so this is just a tiny little PR to fix it.

### CODE REVIEW

**Review by TedDriggs — APPROVED** [review]

**Comment by Adam-Gleave** [comment]
I've just taken a look at those CI errors and I can probably fix these tomorrow (in a separate PR) if there's a want for it -- it just looks like a couple of outdated bits.

**Comment by TedDriggs** [comment]
Ugh - I love Clippy, but I do hate how often PRs are forced to first submit a separate PR that plays catchup with new lints. I'll hit those now.

**Comment by TedDriggs** [comment]
Lot of things went wrong on the CI front. I'm now pushing an update to `darling` so that the 1.59 build will pass, and I'm going to file an issue to get the 1.40 build working again (see dtolnay/trybuild#203), and then finally we'll be able to get #272 to pass CI, which will fix the lint problem, and then we'll be able to see this pass CI and merge it.

**Comment by TedDriggs** [comment]
Okay, please try rebasing now

**Comment by Adam-Gleave** [comment]
Done, thanks. Lots of work for a little typo, was not my original intention!

**Comment by TedDriggs** [comment]
They were updates that needed doing - I'm glad we found out now instead of in another few months!

**Pull request merged**
