### PR TITLE
parse doc comments and visibiliy specifier

### PR DESCRIPTION
**Pull request by colin-kiegel**
implementation according to https://github.com/colin-kiegel/rust-derive-builder/issues/13#issuecomment-238099570

@killercup Seems to work just fine, but it's a delicate / complex macro. At leas a review seems adequate - and we haven't really decided yet.

### CODE REVIEW

**Comment by colin-kiegel** [comment]
PS: current behaviour is 'unexpected token', which could be classified as a bug and is fixed by this PR.

**Comment by killercup** [comment]
Sorry, I'm a bit out of the loop on this—disregard anything that's totally
obvious once I properly look at this.

What are you aiming for with this? Where do you want to skip doc/vis? Can
you add some tests for this change? (Did we add macro-compile tests yet to
compare the expanded tokens? If not, we should probably do that. Should be
possible with static-cond.)


Colin Kiegel <notifications@github.com> schrieb am So., 7. Aug. 2016 um
23:27 Uhr:

**Comment by colin-kiegel** [comment]
this allows public and/or annotated struct fields, by just skipping over
these tokens. The current parser errors with unexpected token in these
cases.

will add a test for this and I might try to combine these matchers to save
iterations. :-)

PS: I was thinking about testing expanded tokens too.

Pascal Hertleif <notifications@github.com> schrieb am Fr., 12. Aug. 2016,
14:56:

**Comment by colin-kiegel** [comment]
Ok, I did this:
* rebased to master
* some additional refactoring / simplification
* and last but not least a new feature: **all** field attributes now map to setter functions

Still work in progress (obviously)
* Travis is failing on stable + beta (I tested only with nightly). Will have a look.
* I am still thinking we should _start_ with whitelisting specific attributes, to be on the safe side (IF that is possible).

PS: I splitted my changes into a history of rather small commits.

**Comment by colin-kiegel** [comment]
I introduced whitelisting of attributes, only these will be added to setter-fns
* `#[doc = ...]`
* `#[cfg(...)]`
* `#[allow(...)]`

If there is demand, we could add these in the future, but I guess they probably make little sense in these positions
* `#[deny(...)]`
* `#[forbid(...)]`
* `#[warn(...)]`

All current attributes are listed here. IMO the rest of them doesn't make sense for setter-fns.
https://doc.rust-lang.org/reference.html#attributes

**Comment by colin-kiegel** [comment]
PS: I also re-ordered most of the arguments to introduce `@foo` as first tokens in recursive calls (where foo = current_state_of_macro, e.g. `parse`).

**Comment by colin-kiegel** [comment]
PPS: If we go along this road, next thing might be to parse and filter the struct-attributes and transfer them to the impl too (candidates again `doc`+`allow`, but `cfg` probably not needed). However I wonder if parsing struct-attributes would survive a possible transition to procedural macros 1.1. Therefore we might wait until then before we do it.

**Comment by colin-kiegel** [comment]
@killercup undid the rebase which caused the trouble - ready for review

**Pull request merged**
