### PR TITLE
docs: remove the obsolete instruction

### PR DESCRIPTION
**Pull request by toku-sa-n**
The `alloc` feature became stable.

### CODE REVIEW

**Comment by TedDriggs** [comment]
#203 has a fix for the error that caused this to fail CI; once that merges I'll also merge this.

**Comment by TedDriggs** [comment]
@toku-sa-n can you please rebase this? Once that's done I think it's good to merge.

**Comment by toku-sa-n** [comment]
Done.

**Comment by TedDriggs** [comment]
Thank you! Once this finishes I'll pull it into master and release 0.10.1 with the `no_std` fix.

**Pull request merged**
