### PR TITLE
Bump rust min version in skeptic and README

### LINKED ISSUE #123: dev/checkfeatures.sh should not rely on rust v1.15
We've moved to a minimum rust version of 1.18.0.

@azriel91, do you mind taking your changes from #111 and making a new PR with them for this issue?

### PR DESCRIPTION
**Pull request by TedDriggs**
@azriel91, please take a look at this if you get a chance. I think your version was more expansive and better.

Fixes #123

### CODE REVIEW

**Comment by Dylan-DPC** [comment]
I prefer taking a slight bigger jump and targetting 1.22.0 as minimum version instead (allows us to use features that were introduced in 1.22.0 and also ensures we make smaller jumps in future)

**Comment by TedDriggs** [comment]
> use features that were introduced in 1.22.0

Which features did you have in mind?

**Comment by Dylan-DPC** [comment]
Right now I don't see anything. But what commonly happens is that if someone wants to PR a change with features that are introduced in the later stages, you end up introducing feature gates ot sticking to older features.

**Comment by TedDriggs** [comment]
> you end up introducing feature gates ot sticking to older features.

My preference at that time would be to bump the min version and the crate's minor version. The [2017 Rust survey](https://blog.rust-lang.org/2017/09/05/Rust-2017-Survey-Results.html#path-to-stability) says most people are on latest stable, so I'm not too worried about leaving people behind when we do have to make those jumps.

**Comment by Dylan-DPC** [comment]
I agree. But then say if there is a crate that is in post-stable stage (post 1.0 release) and every time a dependency shifts its minimum version and they have to do so accordingly, they are in a tough spot. They can't just shift their minimum rust version, because it is a breaking change and they have to release a new major version and wouldn't to do that every time a dependent crate shifts its minimum rust version.

**Comment by TedDriggs** [comment]
> But then say if there is a crate that is in post-stable stage (post 1.0 release)

I don't think this crate is anywhere near stabilization, so I'd rather cross that bridge if we come to it. `darling` is a mandatory dependency in 0.6, and it has a hard dependency on Rust 1.18. I'd rather we not set the minimum version higher than necessary.

**Comment by Dylan-DPC** [comment]
> I don't think this crate is anywhere near stabilization, so I'd rather cross that bridge if we come to it. 

Wasn't referring to this crate, but any crate that uses this one as a dependency. The general consensus on minimum rust version is (stable - 2). Anyway, i'm fine with 1.18 but just that we shouldn't be jumping versions too often.

**Pull request merged**
